apps/student_management/urls.py

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import HodViews, StaffViews, StudentViews
from django.contrib.auth import views as auth_views

from django.views.i18n import set_language

app_name = "student_management"

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', views.homepage, name="homepage"),
    path('login/', views.loginPage, name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('enroll-student/', views.enroll_student, name='enroll_student'),
    path('enroll-success/', views.enroll_success, name='enroll_success'),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('contact/', views.contact, name='contact'),

    path('reinitialisation/', views.CustomPasswordResetView.as_view(), name='custom_password_reset'),
    path('reinitialisation/reussite/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reinitialisation/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
	 name='password_reset_confirm'),
    path('reinitialisation/complet/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
   
    path('set_language/', set_language, name='set_language'),
  

    path('delete_excessive_absences/', HodViews.delete_students_with_excessive_absences, name='delete_students_with_excessive_absences'),
    path('manage_timetable/', HodViews.manage_timetable, name='manage_timetable'),
    path('group_timetable/<int:group_id>/', HodViews.group_timetable, name='group_timetable'),
    path('delete_schedule/<int:schedule_id>', HodViews.delete_schedule, name="delete_schedule"),
    path('delete_group/<int:group_id>/', HodViews.delete_group, name='delete_group'),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('add_student/', HodViews.add_student, name="add_student"),
    path('add_student_save/', HodViews.add_student_save, name="add_student_save"),
    path('manage_student/', HodViews.manage_student, name="manage_student"),
    path('edit_student/<student_id>/', HodViews.edit_student, name="edit_student"),
    path('edit_student_save/', HodViews.edit_student_save, name="edit_student_save"),
    path('delete_student/<student_id>/', HodViews.delete_student, name="delete_student"),
    path('check_email_exist/', HodViews.check_email_exist, name='check_email_exist'),
    path('check_code_PPR_exist/', HodViews.check_code_PPR_exist, name='check_code_PPR_exist'),
    path('check_username_exist/', HodViews.check_username_exist, name='check_username_exist'),
    path('add_staff/', HodViews.add_staff, name="add_staff"),
    path('add_staff_save/', HodViews.add_staff_save, name="add_staff_save"),
    path('manage_staff/', HodViews.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', HodViews.edit_staff, name="edit_staff"),
    path('edit_staff_save/', HodViews.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', HodViews.delete_staff, name="delete_staff"),
    path('add_course/', HodViews.add_course, name="add_course"),
    path('add_course_save/', HodViews.add_course_save, name="add_course_save"),
    path('manage_course/', HodViews.manage_course, name="manage_course"),
    path('edit_course/<course_id>/', HodViews.edit_course, name="edit_course"),
    path('edit_course_save/', HodViews.edit_course_save, name="edit_course_save"),
    path('delete_course/<course_id>/', HodViews.delete_course, name="delete_course"),
    path('admin_view_attendance/', HodViews.admin_view_attendance, name="admin_view_attendance"),
    path('admin_get_attendance_courses/', HodViews.admin_get_attendance_courses, name="admin_get_attendance_courses"),
    path('admin_profile/', HodViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', HodViews.admin_profile_update, name="admin_profile_update"),
    path('manage_staff_groups/', HodViews.manage_staff_groups, name='manage_staff_groups'),
    path('manage_student_groups/', HodViews.manage_student_groups, name='manage_student_groups'),
    path('update_student_group/', HodViews.update_student_group, name='update_student_group'),
    path('update_staff_group/', HodViews.update_staff_group, name='update_staff_group'),
    path('manage_groups/', HodViews.manage_groups, name='manage_groups'),
    path('group/<int:group_id>/', HodViews.group_detail, name='group_detail'),
    path('manage-student-groups/', HodViews.manage_student_groups, name='manage_student_groups'),
    path('update-student-group/', HodViews.update_student_group, name='update_student_group'),
    path('add_group/', HodViews.add_group, name='add_group'),
    path('generate_certificate/<int:project_id>/', HodViews.generate_certificate_view, name='generate_certificate'),
    path('print_certificates/', HodViews.print_certificate_template, name='print_certificate_template'),
    path('admin_get_group_students/', HodViews.admin_get_group_students, name='admin_get_group_students'),
    path('search/', HodViews.search_view, name='search'),

    


    # URLS for Staff
    path('staff_home/', StaffViews.staff_home, name="staff_home"),
    path('staff_take_attendance/', StaffViews.staff_take_attendance, name='staff_take_attendance'),
    path('get_students/<int:groupid>/', StaffViews.get_students, name='get_students'),
    path('save_attendance_data/', StaffViews.save_attendance_data, name="save_attendance_data"),
    path('staff_profile/', StaffViews.staff_profile, name="staff_profile"),
    path('staff_profile_update/', StaffViews.staff_profile_update, name="staff_profile_update"),
    path('add_note/', StaffViews.staff_add_note, name="add_note"),
    path('save_notes_data/', StaffViews.save_notes_data, name="save_notes_data"),
    path('get_groups/<int:course_id>/', StaffViews.get_groups, name='get_groups'),
    path('list_attendances/<int:course_id>/<int:group_id>/', StaffViews.list_attendances, name='list_attendances'),
    path('view_attendance/<int:attendance_id>/', StaffViews.view_attendance, name='view_attendance'),
    path('validate_project/', StaffViews.validate_project, name='validate_project'),
    path('delete_project/<int:project_id>/', StaffViews.delete_project, name='delete_project'),

    # path('search_students/', StaffViews.search_students, name='search_students'),



    # URSL for Student
    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_profile/', StudentViews.student_profile, name="student_profile"),
    path('student_profile_update/', StudentViews.student_profile_update, name="student_profile_update"),
    path('certificate/preview/<int:project_id>/', StudentViews.preview_certificate, name='preview_certificate'),
    path('notes/', StudentViews.get_student_notes, name='get_student_notes'),


    # path('student_view_result/', StudentViews.student_view_result, name="student_view_result"),
]

student_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from student_management_system import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns =[
    path('admin/', admin.site.urls),
    path('', include('apps.student_management.urls', namespace="student_management")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



apps/student_management/models.py

from django.contrib.auth.models import AbstractUser
from django.db import IntegrityError, models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models.signals import m2m_changed
from django.utils import timezone
from django.db.models import Avg, F, FloatField, Sum
from django.utils.functional import cached_property
from django.urls import reverse
from django.utils.html import format_html
from datetime import time
import random



# Overriding the Default Django Auth User and adding One More Field (user_type)
class CustomUser(AbstractUser):
    user_type_data = ((1, "HOD"), (2, "Staff"), (3, "Student"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)

class AdminHOD(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='adminhod')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    
    def generate_certificate_link(self, obj):
        # If the HOD can generate certificates for all students
        url = reverse('generate_certificate')  # You can adjust this if needed
        return format_html('<a href="{}" target="_blank">Generate Certificates</a>', url)
    generate_certificate_link.short_description = 'Generate Certificates'


class Courses(models.Model):
    id = models.AutoField(primary_key=True)
    course_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return self.course_name
    
    def delete(self, *args, **kwargs):
        for student in self.students.all():
            student.courses.remove(self)
        super().delete(*args, **kwargs)



class Day(models.Model):
    DAYS_OF_WEEK = [
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ]

    name = models.CharField(max_length=10, choices=DAYS_OF_WEEK, unique=True)

    def __str__(self):
        return self.name

class GroupSchedule(models.Model):
    group = models.ForeignKey('Group', on_delete=models.CASCADE)
    course = models.ForeignKey('Courses', on_delete=models.CASCADE)
    day_of_week = models.ForeignKey('Day', on_delete=models.CASCADE)  # Use ForeignKey to Day model
    start_time = models.TimeField()
    end_time = models.TimeField()
    category = models.CharField(
        max_length=10,
        choices=[('Morning', 'Morning'), ('Evening', 'Evening')]
    )

    class Meta:
        unique_together = ('group', 'course', 'day_of_week', 'start_time', 'end_time', 'category')
        verbose_name = 'Group Schedule'
        verbose_name_plural = 'Group Schedules'

    def __str__(self):
        return f"{self.group} - {self.course} ({self.category}) on {self.day_of_week} from {self.start_time} to {self.end_time}"

 

class Group(models.Model):
    CATEGORY_CHOICES = [
        ('Morning', 'Morning'),
        ('Evening', 'Evening'),
    ]

    id = models.AutoField(primary_key=True)
    days_of_week = models.ManyToManyField(Day)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
    courses = models.ManyToManyField('Courses') 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def _str_(self):
        return f"{self.category} Group"

    def create_initial_schedule(self):
        courses = list(self.courses.all())
        days_of_week = list(self.days_of_week.all())

        if self.category == 'Morning':
            time_slots = [('08:30', '10:30'), ('10:45', '12:30')]  # Morning session times
        else:
            time_slots = [('13:30', '15:00'), ('15:15', '16:30')]  # Evening session times

        used_courses = set()
        used_days = set()

        for course in courses:
            if course in used_courses:
                continue  # Skip if the course is already scheduled

            for day in days_of_week:
                if day in used_days:
                    continue  # Skip if the day is already used

                for start_time, end_time in time_slots:
                    # Ensure we do not assign overlapping schedules for the same day
                    if not GroupSchedule.objects.filter(
                        group=self, day_of_week=day, start_time=start_time, end_time=end_time
                    ).exists():
                        GroupSchedule.objects.create(
                            group=self,
                            course=course,
                            day_of_week=day,
                            start_time=start_time,
                            end_time=end_time,
                            category=self.category
                        )
                        print(f"Schedule created for group {self}, course {course}, day {day}.")
                        used_courses.add(course)
                        used_days.add(day)
                        break  # Move to the next course after scheduling


@receiver(post_save, sender=Group)
def group_created_handler(sender, instance, created, **kwargs):
    if created:
        instance.create_initial_schedule()




       

class Staffs(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='staffs')
    gender = models.CharField(max_length=50,default="male")
    profile_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    address = models.TextField()
    course = models.ForeignKey(Courses, on_delete=models.DO_NOTHING,default=1)
    groups = models.ManyToManyField(Group)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()




class Students(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='students')
    gender = models.CharField(max_length=50)
    profile_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    address = models.TextField()
    courses = models.ManyToManyField(Courses, related_name='students')
    preferred_category = models.CharField(max_length=10, choices=[('morning', 'Morning'), ('evening', 'Evening')])  
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True)
    grade = models.CharField(max_length=20, choices=[
        ('primaire', 'Primaire'),
        ('college', 'Collège'),
        ('lycee', 'Lycée'),
        ('universite', 'Université'),
        ('superieure', 'Supérieure')
    ])
    code_PPR = models.CharField(max_length=50, null=True,unique=True)
    reference= models.CharField(max_length=100,default="Rabat Sale zamour zaer")
    # blacklisted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.admin.last_name} {self.admin.first_name}"


class NoteType(models.TextChoices):
    ASSIGNMENT = 'A', 'Assignment'
    EXAM = 'E', 'Exam'

class Note(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    note_date = models.DateField(default=timezone.now)
    note_type = models.CharField(max_length=1, choices=NoteType.choices,default="A")
    content = models.TextField(default="0.00")

    def __str__(self):
        return f'Note for {self.student.admin.username} in {self.course.course_name} - {self.get_note_type_display()}'

class Attendance(models.Model):
    id = models.AutoField(primary_key=True)
    attendance_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, default=1)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    objects = models.Manager()

class AttendanceReport(models.Model):
    # Individual Student Attendance
    id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(Students, on_delete=models.DO_NOTHING)
    attendance_id = models.ForeignKey(Attendance, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

class Project(models.Model):
    title = models.CharField(max_length=555)
    encadrant = models.ForeignKey(Staffs, on_delete=models.SET_NULL, null=True, blank=True)
    student = models.ForeignKey('Students', on_delete=models.SET_NULL, null=True, related_name='projects')
    certificate_generated = models.BooleanField(default=False)
    def __str__(self):
        return self.title
    
class Certificat(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='certificates')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='certificates',default="1")  # Add this line
    organization_name = models.CharField(max_length=255, default='C.M.C.F')




class NotificationStudent(models.Model):
    id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(Students, on_delete=models.CASCADE)

apps/student_management/templates/hod_template/add_staff_template.html
{% extends 'hod_template/base_template.html' %}

{% block page_title %}
    Add Staff
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Staff</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'add_staff_save' %}" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% comment %} Display Messages {% endcomment %}
                        {% if messages %}
                        <div class="form-group">
                            <div class="col-12">
                                {% for message in messages %}
                                {% if message.tags == "error" %}
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% elif message.tags == "success" %}
                                    <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        {% endif %}

                        <div class="card-body">
                            <div class="form-group">
                                <label>Email address</label>
                                <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email">
                            </div>

                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control" name="username" placeholder="Username" id="id_username">
                            </div>

                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" name="password" placeholder="Password">
                            </div>

                            <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control" name="first_name" placeholder="First Name">
                            </div>

                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" name="last_name" placeholder="Last Name">
                            </div>

                            <div class="form-group">
                                <label>Address</label>
                                <textarea class="form-control" name="address" placeholder="Address"></textarea>
                            </div>

                            <div class="form-group">
                                <label>Gender</label>
                                <select class="form-control" name="gender">
                                    <option value="male">Male</option>
                                    <option value="female">Female</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="profile_pic">upload profile pic</label>
                                <input type="file" class="form-control-file" id="profile_pic">
                            </div>

                            <div class="form-group">
                                <label>Course</label>
                                <select class="form-control" name="course">
                                    {% for course in courses %}
                                    <option value="{{ course.id }}">{{ course.course_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Add Staff</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

{% endblock main_content %}

{% block custom_js %}
{% comment %} Checking if email and username already exists or not using Ajax {% endcomment %}
<script>
    $(document).ready(function(){
        // keyup event will be triggered when user leaves keyboard
        $("#id_email").keyup(function(){
            var email = $(this).val();
            if(email != ""){
                $.ajax({
                    url : '{% url 'check_email_exist' %}',
                    type : 'POST',
                    data : {email:email}
                })
                .done(function(response){
                    if(response == "True"){
                        $(".email_error").remove();
                        $("<span class='email_error' style='color: red; padding: 5px; font-weight: bold;'> Email Not Available. </span>").insertAfter("#id_email")
                    } else {
                        $(".email_error").remove();
                        $("<span class='email_error' style='color: green; padding: 5px; font-weight: bold;'> Email Available. </span>").insertAfter("#id_email")
                    }
                })
                .fail(function(){
                    console.log("Failed");
                })
            } else {
                $(".email_error").remove();
            }
        })

        $("#id_username").keyup(function(){
            var username = $(this).val();
            if(username != ""){
                $.ajax({
                    url : '{% url 'check_username_exist' %}',
                    type : 'POST',
                    data : {username:username}
                })
                .done(function(response){
                    if(response == "True"){
                        $(".username_error").remove();
                        $("<span class='username_error' style='color: red; padding: 5px; font-weight: bold;'> Username Not Available. </span>").insertAfter("#id_username")
                    } else {
                        $(".username_error").remove();
                        $("<span class='username_error' style='color: green; padding: 5px; font-weight: bold;'> Username Available. </span>").insertAfter("#id_username")
                    }
                })
                .fail(function(){
                    console.log("Failed");
                })
            } else {
                $(".username_error").remove();
            }
        })
    })
</script>
{% endblock custom_js %}

apps/student_management/templates/hod_template/add_student_template.html
{% extends 'hod_template/base_template.html' %}

{% block page_title %}
    Add Student
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add Student</h3>
                        </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    {% url 'add_student_save' as action_path %}
                    {% include 'hod_template/form_template.html' with messages=messages form=form action_path=action_path button_text="Add Student" %}

                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

  {% block custom_js %}
    {% comment %} Checking if email and username already exists or not usin Ajax {% endcomment %}

    <script>
    $(document).ready(function(){
        
            // keyup event will be triggered when user leaves keyboard
            $("#id_email").keyup(function(){
                var email = $(this).val();

                if(email!=""){
                    $.ajax({
                        url : '{% url 'check_email_exist' %}',
                        type : 'POST',
                        data : {email:email},
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: red; padding: 5px; font-weight: bold;'> Email Not Available. </span>").insertAfter("#id_email")
                        }
                        else{
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: green; padding: 5px; font-weight: bold;'> Email Available. </span>").insertAfter("#id_email")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".email_error").remove();
                }
                
            })

            $("#id_username").keyup(function(){
                var username = $(this).val();
                
                if(username!=""){
                    $.ajax({
                        url : '{% url 'check_username_exist' %}',
                        type : 'POST',
                        data : {username:username}
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: red; padding: 5px; font-weight: bold;'> Username Not Available. </span>").insertAfter("#id_username")
                        }
                        else{
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: green; padding: 5px; font-weight: bold;'> Username Available. </span>").insertAfter("#id_username")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".username_error").remove();
                }
                
            })
                // keyup event will be triggered when user leaves keyboard
        $("#id_code_PPR").keyup(function(){
            var code_PPR = $(this).val();

            if(code_PPR != ""){
                $.ajax({
                    url: '{% url 'check_code_PPR_exist' %}',
                    type: 'POST',
                    data: {code_PPR: code_PPR},
                })
                .done(function(response){
                    //console.log(response);

                    if(response == "True"){
                        $(".code_PPR_error").remove();
                        $("<span class='code_PPR_error' style='color: red; padding: 5px; font-weight: bold;'> Code PPR Not Available. </span>").insertAfter("#id_code_PPR");
                    }
                    else{
                        $(".code_PPR_error").remove();
                        $("<span class='code_PPR_error' style='color: green; padding: 5px; font-weight: bold;'> Code PPR Available. </span>").insertAfter("#id_code_PPR");
                    }
                })
                .fail(function(){
                    console.log("Failed");
                });
            }
            else{
                $(".code_PPR_error").remove();
            }
            
        });
    })
    </script>

  {% endblock custom_js %}

apps/student_management/templates/hod_template/footer.html

<footer class="main-footer">
  <strong>Copyright &copy; {% now "Y" %}, <a target="blank" href="https://shorturl.at/QStUE">Center Moroccan Korean Training Technology Information And Communication In Education</a>.</strong> 
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 1.0
  </div>
</footer>